debug: true
server:
  port: 8080
log:
  level: debug
  console: true
  logger:
    filename: .log/course-system.log
    maxsize: 10
database:
  sqlite:
    filename: test.db
token:
  sign-key: SDjhbdsfyg#@&IsaSDJHBVHJSGyeqgwjdhasvdyfGUYWGEYjg2VJWU3jqy2bheqwdsuyTUWYEGJj3h432byjtasbhdhasuye32y4ebwmasdasgdkSDUIHKSsaduiq23SDBVHadjfvbjyg3u4t1i4u1yI#$Y@Ubsadasmnbdhbsad
  storage:
    in-memory:
      file: tokens.json