debug: true
server:
  port: 8080
log:
  level: debug
  console: true
  logger:
    filename: .log/course-system.log
    maxsize: 10
database:
#  postgres:
#    host: 192.168.5.144
#    port: 5432
#    user: postgres
#    password: postgres
#    database: course-system
  sqlite:
    filename: test.db
token:
  sign-key: SDjhbdsfyg#@&IsaSDJHBVHJSGyeqgwjdhasvdyfGUYWGEYjg2VJWU3jqy2bheqwdsuyTUWYEGJj3h432byjtasbhdhasuye32y4ebwmasdasgdkSDUIHKSsaduiq23SDBVHadjfvbjyg3u4t1i4u1yI#$Y@Ubsadasmnbdhbsad
  expire: 240h  # 可用单位："ns", "us" (or "µs"), "ms", "s", "m", "h".
  storage:
    in-memory:
      file: tokens.json